name: ci

on:
  push:
    branches:
      [main]
  pull_request:
    branches: [main]

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest


    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run Server Tests 
        run: cargo test 

  Linting:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run Clippy
        run: cargo clippy -- -D warnings

  Style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Format Rust 
        run: cargo fmt -- --check 

  Security:
    name: Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo audit
        run: cargo install cargo-audit

      - name: Check for Vulnerabilities
        run: cargo audit
